export const DefoultStyle = {
    '&:focus': {outline: 'none'}
}
export const OutlinedWhiteButtonStyle={
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '0px 16px',
    gap: '8px',
    minWidth: '232px',
    minHeight: '40px',
    border: '2px solid #FF9D00',
    borderRadius: '20px 0px',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '24px',
    textAlign: 'center',
    letterSpacing: '0.15px',
}
export const OutlinedWhiteButtonBlackBoardStyle={
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '0px 16px',
    gap: '8px',
    textTransform: 'none',
    minWidth: '232px',
    minHeight: '40px',
    border: ' 1px solid #313030',
    borderRadius: '20px 0px',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '14px',
    lineHeight: '20px',
    textAlign: 'center',
    letterSpacing: '0.1px',
}

export const TransparentButtonStyle= {
    fontFamily: 'Roboto',
    textAlign: 'center',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '0.5px',
    textTransform: 'none',
}
export const TransparentButtonLeftTextStyle= {
    fontFamily: 'Roboto',
    textAlign: 'left',
    alignSelf: 'start',
    justifyContent: 'left',
    padding: 0,
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '0.5px',
    textTransform: 'none',
}
export const TransparentSmallButtonStyle= {
    fontFamily: 'Roboto',
    textAlign: 'center',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '20px',
    letterSpacing: '0.1px',
    textTransform: 'none',
}
export const OrangeRoundButtonStyle= {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '0px 24px 0px 16px',
    gap: '8px',
    borderRadius: '20px',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '20px',
    letterSpacing: '0.1px',
}

export const CarouselButtonStyle = {
    minWidth: 50,
    margin: 0,
    width: 'fit-content',
    borderRadius: 30,
    fontsize: 14,
    fontFamily: 'Roboto',
    textTransform: 'none',
    display: 'flex',
    flexDirection: 'row',
    flexGrow: 0,
    boxSizing: 'border-box',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '0px 24px',
    gap: 16,
    height: 48,
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: 24,
    lineHeight: 28,
    textAlign: 'center',
}
export const AppButtonRefStyle={
    height: 48,
    minWidth: 216,
    marginLeft: 5,
    marginRight: 5,
    borderRadius: 30,
    fontsize: 14,
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    textTransform: 'none'
}

export const BreadCrampsButtonStyle={
    fontFamily: 'Roboto',
    textAlign: 'center',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '22px',
    lineHeight: '28px',
    textTransform: 'none',
    padding: 0,
}